config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controlles: { }
    # devise_for :members do 
    #     get '/members/sign_out' => 'devise/sessions#destroy' 
    # end
    root to: 'dashboards#show'
    resources :costs
    resources :attendances
    resources :schedulings
    resources :cashes
    resources :providers
    resources :bank_accounts
    resources :bank_names
    resources :stocks
    resources :operations
    resources :operation_types
    resources :products
    resources :product_unit_measurements
    resources :product_colors
    resources :product_sizes
    resources :product_brands
    resources :product_categories
    resources :product_types
    resources :payment_methods
    resources :cost_types
    resources :status_schedulings
    resources :status_users
    resources :services
    resources :companies
    resources :users
    resources :addresses
    resources :profiles
    get '/dashboards', to: 'dashboards#show'


    post '/admins_create', to: 'users#create_user'
    get '/sessions/sign_out', to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :service
  belongs_to :product
  belongs_to :payment_method
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :bank_name
  belongs_to :company
end

app/models/bank_name.rb
class BankName < ApplicationRecord
end

app/models/cash.rb
class Cash < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :address, optional: true
  has_many :bank_accounts
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :cost_type
  belongs_to :payment_method
end

app/models/cost_type.rb
class CostType < ApplicationRecord
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :product
  belongs_to :company
  belongs_to :operation_type
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :address
  belongs_to :company
end

app/models/scheduling.rb
class Scheduling < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :status_scheduling
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :company
end

app/models/status_user.rb
class StatusUser < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :profile, optional: true
  belongs_to :status_user, optional: true
  belongs_to :address, optional: true

  paginates_per 10

end

app/controllers/product_types_controller.rb
class ProductTypesController < ApplicationController
  before_action :set_product_type, only: [:show, :edit, :update, :destroy]

  # GET /product_types
  # GET /product_types.json
  def index
    @product_types = ProductType.all
  end

  # GET /product_types/1
  # GET /product_types/1.json
  def show
  end

  # GET /product_types/new
  def new
    @product_type = ProductType.new
  end

  # GET /product_types/1/edit
  def edit
  end

  # POST /product_types
  # POST /product_types.json
  def create
    @product_type = ProductType.new(product_type_params)

    respond_to do |format|
      if @product_type.save
        format.html { redirect_to @product_type, notice: 'Product type was successfully created.' }
        format.json { render :show, status: :created, location: @product_type }
      else
        format.html { render :new }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_types/1
  # PATCH/PUT /product_types/1.json
  def update
    respond_to do |format|
      if @product_type.update(product_type_params)
        format.html { redirect_to @product_type, notice: 'Product type was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_type }
      else
        format.html { render :edit }
        format.json { render json: @product_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_types/1
  # DELETE /product_types/1.json
  def destroy
    @product_type.destroy
    respond_to do |format|
      format.html { redirect_to product_types_url, notice: 'Product type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_type
      @product_type = ProductType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_type_params
      params.require(:product_type).permit(:description)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/product_types_helper.rb
module ProductTypesHelper
end

app/views/product_types/_form.html.erb
<%= form_with(model: product_type, local: true) do |form| %>
  <% if product_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product_type.errors.count, "error") %> prohibited this product_type from being saved:</h2>

      <ul>
        <% product_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/product_types/edit.html.erb
<h1>Editing Product Type</h1>

<%= render 'form', product_type: @product_type %>

<%= link_to 'Show', @product_type %> |
<%= link_to 'Back', product_types_path %>

app/views/product_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Types</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_types.each do |product_type| %>
      <tr>
        <td><%= product_type.description %></td>
        <td><%= link_to 'Show', product_type %></td>
        <td><%= link_to 'Edit', edit_product_type_path(product_type) %></td>
        <td><%= link_to 'Destroy', product_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product Type', new_product_type_path %>

app/views/product_types/new.html.erb
<h1>New Product Type</h1>

<%= render 'form', product_type: @product_type %>

<%= link_to 'Back', product_types_path %>

app/views/product_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @product_type.description %>
</p>

<%= link_to 'Edit', edit_product_type_path(@product_type) %> |
<%= link_to 'Back', product_types_path %>