config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controlles: { }
    # devise_for :members do 
    #     get '/members/sign_out' => 'devise/sessions#destroy' 
    # end
    root to: 'dashboards#show'
    resources :costs
    resources :attendances
    resources :schedulings
    resources :cashes
    resources :providers
    resources :bank_accounts
    resources :bank_names
    resources :stocks
    resources :operations
    resources :operation_types
    resources :products
    resources :product_unit_measurements
    resources :product_colors
    resources :product_sizes
    resources :product_brands
    resources :product_categories
    resources :product_types
    resources :payment_methods
    resources :cost_types
    resources :status_schedulings
    resources :status_users
    resources :services
    resources :companies
    resources :users
    resources :addresses
    resources :profiles
    get '/dashboards', to: 'dashboards#show'


    post '/admins_create', to: 'users#create_user'
    get '/sessions/sign_out', to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :service
  belongs_to :product
  belongs_to :payment_method
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :bank_name
  belongs_to :company
end

app/models/bank_name.rb
class BankName < ApplicationRecord
end

app/models/cash.rb
class Cash < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :address, optional: true
  has_many :bank_accounts
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :cost_type
  belongs_to :payment_method
end

app/models/cost_type.rb
class CostType < ApplicationRecord
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :product
  belongs_to :company
  belongs_to :operation_type
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :address
  belongs_to :company
end

app/models/scheduling.rb
class Scheduling < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :status_scheduling
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :company
end

app/models/status_user.rb
class StatusUser < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :profile, optional: true
  belongs_to :status_user, optional: true
  belongs_to :address, optional: true

  paginates_per 10

end

app/controllers/operation_types_controller.rb
class OperationTypesController < ApplicationController
  before_action :set_operation_type, only: [:show, :edit, :update, :destroy]

  # GET /operation_types
  # GET /operation_types.json
  def index
    @operation_types = OperationType.all
  end

  # GET /operation_types/1
  # GET /operation_types/1.json
  def show
  end

  # GET /operation_types/new
  def new
    @operation_type = OperationType.new
  end

  # GET /operation_types/1/edit
  def edit
  end

  # POST /operation_types
  # POST /operation_types.json
  def create
    @operation_type = OperationType.new(operation_type_params)

    respond_to do |format|
      if @operation_type.save
        format.html { redirect_to @operation_type, notice: 'Operation type was successfully created.' }
        format.json { render :show, status: :created, location: @operation_type }
      else
        format.html { render :new }
        format.json { render json: @operation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operation_types/1
  # PATCH/PUT /operation_types/1.json
  def update
    respond_to do |format|
      if @operation_type.update(operation_type_params)
        format.html { redirect_to @operation_type, notice: 'Operation type was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation_type }
      else
        format.html { render :edit }
        format.json { render json: @operation_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operation_types/1
  # DELETE /operation_types/1.json
  def destroy
    @operation_type.destroy
    respond_to do |format|
      format.html { redirect_to operation_types_url, notice: 'Operation type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation_type
      @operation_type = OperationType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_type_params
      params.require(:operation_type).permit(:description)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/operation_types_helper.rb
module OperationTypesHelper
end

app/views/operation_types/_form.html.erb
<%= form_with(model: operation_type, local: true) do |form| %>
  <% if operation_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operation_type.errors.count, "error") %> prohibited this operation_type from being saved:</h2>

      <ul>
        <% operation_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/operation_types/edit.html.erb
<h1>Editing Operation Type</h1>

<%= render 'form', operation_type: @operation_type %>

<%= link_to 'Show', @operation_type %> |
<%= link_to 'Back', operation_types_path %>

app/views/operation_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operation Types</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operation_types.each do |operation_type| %>
      <tr>
        <td><%= operation_type.description %></td>
        <td><%= link_to 'Show', operation_type %></td>
        <td><%= link_to 'Edit', edit_operation_type_path(operation_type) %></td>
        <td><%= link_to 'Destroy', operation_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation Type', new_operation_type_path %>

app/views/operation_types/new.html.erb
<h1>New Operation Type</h1>

<%= render 'form', operation_type: @operation_type %>

<%= link_to 'Back', operation_types_path %>

app/views/operation_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Description:</strong>
  <%= @operation_type.description %>
</p>

<%= link_to 'Edit', edit_operation_type_path(@operation_type) %> |
<%= link_to 'Back', operation_types_path %>