config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controlles: { }
    # devise_for :members do 
    #     get '/members/sign_out' => 'devise/sessions#destroy' 
    # end
    root to: 'dashboards#show'
    resources :costs
    resources :attendances
    resources :schedulings
    resources :cashes
    resources :providers
    resources :bank_accounts
    resources :bank_names
    resources :stocks
    resources :operations
    resources :operation_types
    resources :products
    resources :product_unit_measurements
    resources :product_colors
    resources :product_sizes
    resources :product_brands
    resources :product_categories
    resources :product_types
    resources :payment_methods
    resources :cost_types
    resources :status_schedulings
    resources :status_users
    resources :services
    resources :companies
    resources :users
    resources :addresses
    resources :profiles
    get '/dashboards', to: 'dashboards#show'


    post '/admins_create', to: 'users#create_user'
    get '/sessions/sign_out', to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :service
  belongs_to :product
  belongs_to :payment_method
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :bank_name
  belongs_to :company
end

app/models/bank_name.rb
class BankName < ApplicationRecord
end

app/models/cash.rb
class Cash < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :address, optional: true
  has_many :bank_accounts
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :cost_type
  belongs_to :payment_method
end

app/models/cost_type.rb
class CostType < ApplicationRecord
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :product
  belongs_to :company
  belongs_to :operation_type
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
end

app/models/product_brand.rb
class ProductBrand < ApplicationRecord
end

app/models/product_color.rb
class ProductColor < ApplicationRecord
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :address
  belongs_to :company
end

app/models/scheduling.rb
class Scheduling < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :status_scheduling
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :company
end

app/models/status_user.rb
class StatusUser < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :profile, optional: true
  belongs_to :status_user, optional: true
  belongs_to :address, optional: true

  paginates_per 10

end

app/controllers/costs_controller.rb
class CostsController < ApplicationController
  before_action :set_cost, only: [:show, :edit, :update, :destroy]

  # GET /costs
  # GET /costs.json
  def index
    @costs = Cost.all
  end

  # GET /costs/1
  # GET /costs/1.json
  def show
  end

  # GET /costs/new
  def new
    @cost = Cost.new
  end

  # GET /costs/1/edit
  def edit
  end

  # POST /costs
  # POST /costs.json
  def create
    @cost = Cost.new(cost_params)

    respond_to do |format|
      if @cost.save
        format.html { redirect_to @cost, notice: 'Cost was successfully created.' }
        format.json { render :show, status: :created, location: @cost }
      else
        format.html { render :new }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /costs/1
  # PATCH/PUT /costs/1.json
  def update
    respond_to do |format|
      if @cost.update(cost_params)
        format.html { redirect_to @cost, notice: 'Cost was successfully updated.' }
        format.json { render :show, status: :ok, location: @cost }
      else
        format.html { render :edit }
        format.json { render json: @cost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /costs/1
  # DELETE /costs/1.json
  def destroy
    @cost.destroy
    respond_to do |format|
      format.html { redirect_to costs_url, notice: 'Cost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cost
      @cost = Cost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def cost_params
      params.require(:cost).permit(:value, :description, :cost_type_id, :payment_method_id)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/costs/_form.html.erb
<%= form_with(model: cost, local: true) do |form| %>
  <% if cost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cost.errors.count, "error") %> prohibited this cost from being saved:</h2>

      <ul>
        <% cost.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :value %>
    <%= form.number_field :value %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :cost_type_id %>
    <%= form.text_field :cost_type_id %>
  </div>

  <div class="field">
    <%= form.label :payment_method_id %>
    <%= form.text_field :payment_method_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/costs/edit.html.erb
<h1>Editing Cost</h1>

<%= render 'form', cost: @cost %>

<%= link_to 'Show', @cost %> |
<%= link_to 'Back', costs_path %>

app/views/costs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Costs</h1>

<table>
  <thead>
    <tr>
      <th>Value</th>
      <th>Description</th>
      <th>Cost type</th>
      <th>Payment method</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @costs.each do |cost| %>
      <tr>
        <td><%= cost.value %></td>
        <td><%= cost.description %></td>
        <td><%= cost.cost_type_id %></td>
        <td><%= cost.payment_method_id %></td>
        <td><%= link_to 'Show', cost %></td>
        <td><%= link_to 'Edit', edit_cost_path(cost) %></td>
        <td><%= link_to 'Destroy', cost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cost', new_cost_path %>

app/views/costs/new.html.erb
<h1>New Cost</h1>

<%= render 'form', cost: @cost %>

<%= link_to 'Back', costs_path %>

app/views/costs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Value:</strong>
  <%= @cost.value %>
</p>

<p>
  <strong>Description:</strong>
  <%= @cost.description %>
</p>

<p>
  <strong>Cost type:</strong>
  <%= @cost.cost_type_id %>
</p>

<p>
  <strong>Payment method:</strong>
  <%= @cost.payment_method_id %>
</p>

<%= link_to 'Edit', edit_cost_path(@cost) %> |
<%= link_to 'Back', costs_path %>