config/routes.rb
Rails.application.routes.draw do
    devise_for :users, controlles: { }
    # devise_for :members do 
    #     get '/members/sign_out' => 'devise/sessions#destroy' 
    # end
    root to: 'dashboards#show'
    resources :costs
    resources :attendances
    resources :schedulings
    resources :cashes
    resources :providers
    resources :bank_accounts
    resources :bank_names
    resources :stocks
    resources :operations
    resources :operation_types
    resources :products
    resources :product_unit_measurements
    resources :product_colors
    resources :product_sizes
    resources :product_brands
    resources :product_categories
    resources :product_types
    resources :payment_methods
    resources :cost_types
    resources :status_schedulings
    resources :status_users
    resources :services
    resources :companies
    resources :users
    resources :addresses
    resources :profiles
    get '/dashboards', to: 'dashboards#show'


    post '/admins_create', to: 'users#create_user'
    get '/sessions/sign_out', to: 'sessions#destroy'
end

app/models/address.rb
class Address < ApplicationRecord
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :service
  belongs_to :product
  belongs_to :payment_method
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :bank_name
  belongs_to :company
end

app/models/bank_name.rb
class BankName < ApplicationRecord
end

app/models/cash.rb
class Cash < ApplicationRecord
  belongs_to :company
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :address, optional: true
  has_many :bank_accounts
end

app/models/cost.rb
class Cost < ApplicationRecord
  belongs_to :cost_type
  belongs_to :payment_method
end

app/models/cost_type.rb
class CostType < ApplicationRecord
end

app/models/operation.rb
class Operation < ApplicationRecord
  belongs_to :product
  belongs_to :company
  belongs_to :operation_type
end

app/models/operation_type.rb
class OperationType < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :company
end

app/models/product_size.rb
class ProductSize < ApplicationRecord
end

app/models/product_type.rb
class ProductType < ApplicationRecord
end

app/models/profile.rb
class Profile < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
  belongs_to :address
  belongs_to :company
end

app/models/scheduling.rb
class Scheduling < ApplicationRecord
  belongs_to :user
  belongs_to :company
  belongs_to :status_scheduling
  belongs_to :service
end

app/models/service.rb
class Service < ApplicationRecord
  belongs_to :company
end

app/models/status_user.rb
class StatusUser < ApplicationRecord
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
  belongs_to :company
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :profile, optional: true
  belongs_to :status_user, optional: true
  belongs_to :address, optional: true

  paginates_per 10

end

app/controllers/operations_controller.rb
class OperationsController < ApplicationController
  before_action :set_operation, only: [:show, :edit, :update, :destroy]

  # GET /operations
  # GET /operations.json
  def index
    @operations = Operation.all
  end

  # GET /operations/1
  # GET /operations/1.json
  def show
  end

  # GET /operations/new
  def new
    @operation = Operation.new
  end

  # GET /operations/1/edit
  def edit
  end

  # POST /operations
  # POST /operations.json
  def create
    @operation = Operation.new(operation_params)

    respond_to do |format|
      if @operation.save
        format.html { redirect_to @operation, notice: 'Operation was successfully created.' }
        format.json { render :show, status: :created, location: @operation }
      else
        format.html { render :new }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operations/1
  # PATCH/PUT /operations/1.json
  def update
    respond_to do |format|
      if @operation.update(operation_params)
        format.html { redirect_to @operation, notice: 'Operation was successfully updated.' }
        format.json { render :show, status: :ok, location: @operation }
      else
        format.html { render :edit }
        format.json { render json: @operation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operations/1
  # DELETE /operations/1.json
  def destroy
    @operation.destroy
    respond_to do |format|
      format.html { redirect_to operations_url, notice: 'Operation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operation
      @operation = Operation.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def operation_params
      params.require(:operation).permit(:quantity, :discount, :subtotal, :total, :product_id, :company_id, :operation_type_id)
    end
end

app/helpers/costs_helper.rb
module CostsHelper
end

app/helpers/operations_helper.rb
module OperationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/operations/_form.html.erb
<%= form_with(model: operation, local: true) do |form| %>
  <% if operation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(operation.errors.count, "error") %> prohibited this operation from being saved:</h2>

      <ul>
        <% operation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :quantity %>
    <%= form.text_field :quantity %>
  </div>

  <div class="field">
    <%= form.label :discount %>
    <%= form.text_field :discount %>
  </div>

  <div class="field">
    <%= form.label :subtotal %>
    <%= form.text_field :subtotal %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="field">
    <%= form.label :company_id %>
    <%= form.text_field :company_id %>
  </div>

  <div class="field">
    <%= form.label :operation_type_id %>
    <%= form.text_field :operation_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/operations/edit.html.erb
<h1>Editing Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Show', @operation %> |
<%= link_to 'Back', operations_path %>

app/views/operations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Operations</h1>

<table>
  <thead>
    <tr>
      <th>Quantity</th>
      <th>Discount</th>
      <th>Subtotal</th>
      <th>Total</th>
      <th>Product</th>
      <th>Company</th>
      <th>Operation type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @operations.each do |operation| %>
      <tr>
        <td><%= operation.quantity %></td>
        <td><%= operation.discount %></td>
        <td><%= operation.subtotal %></td>
        <td><%= operation.total %></td>
        <td><%= operation.product_id %></td>
        <td><%= operation.company_id %></td>
        <td><%= operation.operation_type_id %></td>
        <td><%= link_to 'Show', operation %></td>
        <td><%= link_to 'Edit', edit_operation_path(operation) %></td>
        <td><%= link_to 'Destroy', operation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operation', new_operation_path %>

app/views/operations/new.html.erb
<h1>New Operation</h1>

<%= render 'form', operation: @operation %>

<%= link_to 'Back', operations_path %>

app/views/operations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantity:</strong>
  <%= @operation.quantity %>
</p>

<p>
  <strong>Discount:</strong>
  <%= @operation.discount %>
</p>

<p>
  <strong>Subtotal:</strong>
  <%= @operation.subtotal %>
</p>

<p>
  <strong>Total:</strong>
  <%= @operation.total %>
</p>

<p>
  <strong>Product:</strong>
  <%= @operation.product_id %>
</p>

<p>
  <strong>Company:</strong>
  <%= @operation.company_id %>
</p>

<p>
  <strong>Operation type:</strong>
  <%= @operation.operation_type_id %>
</p>

<%= link_to 'Edit', edit_operation_path(@operation) %> |
<%= link_to 'Back', operations_path %>